#############################################################################
# Makefile for building: tweetian_0xA00158E5
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 12. ??? 00:59:31 2021
# Project:  discordsymbian.pro
# Template: app
# Command: c:\qtsdk\symbian\sdks\symbian3qt474\bin\qmake.exe -spec c:\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf discordsymbian.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbian3qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DAPP_VERSION="1.8.3" -DQ_COMPONENTS_SYMBIAN -DHAVE_MOBILITY -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtCore"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtNetwork"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtGui"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtDeclarative"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/mkspecs/common/symbian"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis/sys"  -I"C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/qmlapplicationviewer"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/mw"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/loc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw/loc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis/stlportv5"  -I"C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/moc"  -I"C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/src/cpp"  -I"C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/src"  -I"C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/discordsymbian.pro"  -spec c:\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/discordsymbian.pro
	$(QMAKE) "C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/discordsymbian.pro"  -spec c:\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc: 
	$(QMAKE) "C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/discordsymbian.pro"  -spec c:\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/release/winscw/udeb/tweetian_0xA00158E5.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis tweetian_0xA00158E5.sis tweetian_0xA00158E5.exe $(QT_RUN_OPTIONS)

tweetian_0xA00158E5_template.pkg: C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/discordsymbian.pro
	$(MAKE) -f $(MAKEFILE) qmake

tweetian_0xA00158E5_installer.pkg: C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/discordsymbian.pro
	$(MAKE) -f $(MAKEFILE) qmake

tweetian_0xA00158E5_stub.pkg: C:/Users/RuzikNF/Documents/Projects/discord-symbian/discord-symbian/discordsymbian.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: tweetian_0xA00158E5_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) tweetian_0xA00158E5_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: tweetian_0xA00158E5_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o tweetian_0xA00158E5_template.pkg $(QT_SIS_TARGET)

tweetian_0xA00158E5.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: tweetian_0xA00158E5_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: tweetian_0xA00158E5_installer.pkg
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) tweetian_0xA00158E5_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: tweetian_0xA00158E5_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: tweetian_0xA00158E5_installer.pkg
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o tweetian_0xA00158E5_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: tweetian_0xA00158E5_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) tweetian_0xA00158E5_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call tweetian_0xA00158E5.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_Socket.cpp moc\moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_Socket.cpp moc\moc_qmlapplicationviewer.cpp
moc\moc_Socket.cpp: src\cpp\Socket.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\src\cpp\Socket.h -o c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\moc\moc_Socket.cpp

moc\moc_qmlapplicationviewer.cpp: qmlapplicationviewer\qmlapplicationviewer.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\qmlapplicationviewer\qmlapplicationviewer.h -o c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\moc\moc_qmlapplicationviewer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

dodistclean:
	-@ if EXIST "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5_template.pkg" $(DEL_FILE)  "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5_template.pkg"
	-@ if EXIST "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5_stub.pkg" $(DEL_FILE)  "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5_stub.pkg"
	-@ if EXIST "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5_installer.pkg" $(DEL_FILE)  "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5_installer.pkg"
	-@ if EXIST "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\Makefile" $(DEL_FILE)  "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\Makefile"
	-@ if EXIST "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5_exe.mmp" $(DEL_FILE)  "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5_exe.mmp"
	-@ if EXIST "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5_reg.rss" $(DEL_FILE)  "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5_reg.rss"
	-@ if EXIST "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.rss" $(DEL_FILE)  "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.rss"
	-@ if EXIST "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc" $(DEL_FILE)  "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\tweetian_0xA00158E5.loc"
	-@ if EXIST "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\bld.inf" $(DEL_FILE)  "c:\Users\RuzikNF\Documents\Projects\discord-symbian\discord-symbian\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


